### ISSUE TITLE
CSS for dmc.CodeHighlight component is missing.

### ISSUE THREAD

**Issue by snehilvj** [AnnMarieW/dash-pylette#1]
CSS for CodeHighlight needs to be passed in external_stylesheets.

**Comment by AnnMarieW** [comment]
Hi @snehilvj 

Thanks for the tip!  Yes, I forgot the CodeHighlight stylesheet, but when I tried adding it,  I preferred it as-is.  It's only one line of code and I like the bright left-aligned copy button for this app :-)
